name: aimind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  icons_plus: ^5.0.0
  sign_in_button: ^3.2.0
  supabase_flutter: ^2.8.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/google_logo.png
    - assets/images/x_logo.png
    - .env
