name: aimind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  app_links: ^6.4.0
  change_app_package_name: ^1.4.0
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_facebook_auth: ^7.1.1
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  http: ^1.3.0
  icons_plus: ^5.0.0
  rive_animated_icon: ^2.0.3
  sign_in_button: ^3.2.0
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.8.3
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/google_logo.png
    - assets/images/x_logo.png
    - assets/images/Psic1.jpg
    - assets/images/Psic2.png
    - .env